{% set version = "0.15" %}

package:
  name: r-repr
  version: {{ version }}

source:
  fn: r-repr-{{ version }}.tar.gz
  url: https://github.com/IRkernel/repr/archive/{{ version }}.tar.gz
  sha256: f905803fd6dd35cd9ca56b24a2f290c9ea2c2c5578cdc1753c44c07ca5545d06

build:
  number: 0
  skip: True  # [win32]
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - posix  # [win64]
    - m2-git  # [win64]
    - r-htmltools
    - r-base64enc
  run:
    - r-base
    - r-htmltools
    - r-base64enc

test:
  commands:
    - R -e "library('repr')"  # [not win]
    - R -e \"library('repr')\"  # [win]

about:
  home: https://github.com/IRkernel/repr
  license: GPL-3
  summary: 'String and binary representations of objects for several formats / mime types.'

extra:
  recipe-maintainers:
    - ocefpaf
