{% set version = "0.19.2" %}

package:
  name: r-repr
  version: {{ version }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/repr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/repr/repr_{{ version }}.tar.gz
  sha256: dd4d766d95e8e75f90c05e50e44e759139a47b1477748f4cf9683d35a7fa10d6

build:
  noarch: generic
  number: 0
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-base64enc
    - r-htmltools
    - r-jsonlite
  run:
    - r-base
    - r-base64enc
    - r-htmltools
    - r-jsonlite

test:
  commands:
    - R -e "library('repr')"

about:
  home: https://CRAN.R-project.org/package=repr
  license: GPL-3.0
  license_family: GPL3
  summary: String and binary representations of objects for several formats / mime types.

extra:
  recipe-maintainers:
    - ocefpaf
