{% set version = "0.12" %}

package:
  name: r-repr
  version: {{ version }}

source:
  fn: r-repr-{{ version }}.tar.gz
  url: https://github.com/IRkernel/repr/archive/{{ version }}.tar.gz
  sha256: 0a11412a27167123231536262a11223f1e7007c7e4f257fcb85a7c1aa076a0d5

build:
  number: 0
  skip: True  # [win32]
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:  # [not win32]
  build:  # [not win32]
    - r-base  # [not win32]
    - posix  # [win64]
    - m2-git  # [win64]
  run:  # [not win32]
    - r-base  # [not win32]

test:
  commands:
    - R -e "library('repr')"  # [not win]
    - R -e \"library('repr')\"  # [win]

about:
  home: https://github.com/IRkernel/repr
  license: GPL-3
  summary: 'String and binary representations of objects for several formats / mime types.'

extra:
  recipe-maintainers:
    - ocefpaf
