{% set version = "0.19.1" %}

package:
  name: r-repr
  version: {{ version }}

source:
  fn: r-repr-{{ version }}.tar.gz
  url: https://github.com/IRkernel/repr/archive/{{ version }}.tar.gz
  sha256: 21e96055605a3516785c6a7729c9c9061d87b10a1dbe5178e2b77ba9fc3bc897

build:
  noarch: generic
  number: 1000
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-htmltools
    - r-base64enc
  run:
    - r-base
    - r-htmltools
    - r-base64enc

test:
  commands:
    - R -e "library('repr')"

about:
  home: https://github.com/IRkernel/repr
  license: GPL-3.0
  summary: 'String and binary representations of objects for several formats / mime types.'

extra:
  recipe-maintainers:
    - ocefpaf
