travis:
  secure:
    BINSTAR_TOKEN: JHqzyadjUuPeCV4CC9MejxxEgevZ0CrrgxoNgdqFJC9ARgL1haPyjW1WU74n/Pw+38//RcJFeY4lwzOlnz8fUqm/fxwDe93e5Fck4r4/wz5wR3iAtVh+1ld3kV9iJL+VRBQrIgkOG36x3qcGCGtMTPpM4490iVr1HmlDWUQXfjCsPP5lA379iUXzL4dpUISvYCsfB/kM7M9FOOhmWjEAc5GBkoaPUyg2tJ/wZhca3kkaU9w9thS6ypUfQTlqnrOkku/YpYIPqBix5hGvhTusRGtxEAiNd2hqYzcAhZI5+zoD1GeJec339ZrXxJuoNg7mgd6govQoBfBO23aMV38LaOKcsncC8lxbmzANSCtXagWAwAKyUf3XKQ1ZKLwtCI6qaC0rkg9aMJQakuwT3QoGEaLsewNhAiGmTp9oMjR+QhDqwsuCA3qE+vM0BH/hnlvsNV8YeKyf1qSkLlFh9lMaV71tAxjLzy45qKzjWUmTK4OTkgh4EjfV08YezRlhO2HdInce4XkEJbu+cps6J3rihJ3y01QbCQmoFPtMGVkAgzuOyRq5LhQq1XyCgA9hnDt4IHn0zK8WtIeq3EKBJO89IOnBk+asVzDDy/kiSrvpnYRHTfE4doHtq61jy03nCp5DjGm/s36r76EBRjcb2xHIHYp8bMCHJyS1uvxdap+CVmI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
